Fix truncated mypy errors by setting `--no-pretty` (#17564)
This fixes an issue when the error text gets truncated because of
project local settings. As you can see from the example below, the
output with `--pretty` is wrapped (at 80 chars?) when piped.

The wrapped lines are truncated from the error message.

```console
$ cat > pyproject.toml <<<EOF
[tool.mypy]
pretty = true
EOF

$ cat > foobar.py <<<
def foobar(a: int):
    pass

foobar("123")
EOF

$ mypy foobar.py
foobar.py:5: error: Argument 1 to "foobar" has incompatible type "str"; expected "int"
    foobar("123")
           ^
Found 1 error in 1 file (checked 1 source file)

$ mypy foobar.py | cat
foobar.py:5: error: Argument 1 to "foobar" has incompatible type "str";
expected "int"
    foobar("123")
           ^
Found 1 error in 1 file (checked 1 source file)

$ mypy --no-pretty foobar.py
foobar.py:5: error: Argument 1 to "foobar" has incompatible type "str"; expected "int"
Found 1 error in 1 file (checked 1 source file)

$ mypy --no-pretty foobar.py | cat
foobar.py:5: error: Argument 1 to "foobar" has incompatible type "str"; expected "int"
Found 1 error in 1 file (checked 1 source file)
```